// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFLu_iDOzUcMlKDSEEhUGrsNKjiEjzBhE',
    appId: '1:768842528474:web:0ef09d2546f5aa695497e3',
    messagingSenderId: '768842528474',
    projectId: 'worldscout-9d813',
    authDomain: 'worldscout-9d813.firebaseapp.com',
    databaseURL: 'https://worldscout-9d813-default-rtdb.firebaseio.com',
    storageBucket: 'worldscout-9d813.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBogDmaLGhzQAsJWHXgjKb8NkQIaibZp8g',
    appId: '1:768842528474:android:6ed9c918927b79c85497e3',
    messagingSenderId: '768842528474',
    projectId: 'worldscout-9d813',
    databaseURL: 'https://worldscout-9d813-default-rtdb.firebaseio.com',
    storageBucket: 'worldscout-9d813.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABT_RtMX1RZDwePhZVM8Dq4ruGRN1PBQ4',
    appId: '1:768842528474:ios:ef8db32e61219cc35497e3',
    messagingSenderId: '768842528474',
    projectId: 'worldscout-9d813',
    databaseURL: 'https://worldscout-9d813-default-rtdb.firebaseio.com',
    storageBucket: 'worldscout-9d813.firebasestorage.app',
    iosBundleId: 'com.example.worldscout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABT_RtMX1RZDwePhZVM8Dq4ruGRN1PBQ4',
    appId: '1:768842528474:ios:ef8db32e61219cc35497e3',
    messagingSenderId: '768842528474',
    projectId: 'worldscout-9d813',
    databaseURL: 'https://worldscout-9d813-default-rtdb.firebaseio.com',
    storageBucket: 'worldscout-9d813.firebasestorage.app',
    iosBundleId: 'com.example.worldscout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFLu_iDOzUcMlKDSEEhUGrsNKjiEjzBhE',
    appId: '1:768842528474:web:168300bef774e21f5497e3',
    messagingSenderId: '768842528474',
    projectId: 'worldscout-9d813',
    authDomain: 'worldscout-9d813.firebaseapp.com',
    databaseURL: 'https://worldscout-9d813-default-rtdb.firebaseio.com',
    storageBucket: 'worldscout-9d813.firebasestorage.app',
  );
}
